[package]
name = "hc_save_conv"
version = "0.1.0"
edition = "2021"
authors = ["nekoinemo@gmail.com"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
serde_json = "1.0.132"
